/**
 * @module apps/traffic-web-app/frontend/src/components/landing/DataModelsShowcase
 * @author Nguyen Dinh Anh Tuan
 * @created 2025-11-28
 * @modified 2025-11-28
 * @version 1.3.0
 * @license MIT
 * 
 * @description
 * Interactive data model showcase demonstrating 9 NGSI-LD Smart Data Models used in the
 * system. Features tabbed interface with expandable JSON-LD examples, entity relationships,
 * and semantic annotations. Educates users about FIWARE standards and Linked Data principles.
 * 
 * Core features:
 * - 9 selectable data models (Camera, Weather, AirQuality, Accident, etc.)
 * - Color-coded model cards with icons
 * - Expandable JSON-LD code snippets
 * - Context and relationship explanations
 * - Animated tab transitions
 * - Syntax-highlighted JSON display
 * 
 * @dependencies
 * - react@18.2.0 - Component state and hooks
 * - framer-motion@10.16.1 - Tab and content animations
 * - lucide-react@0.263.1 - Model icons (Camera, Cloud, Wind, etc.)
 * 
 * @example
 * ```tsx
 * <DataModelsShowcase />
 * ```
 */
import { motion } from 'framer-motion';
import { Camera, Cloud, Wind, AlertTriangle, TrendingUp, Database, MapPin, Users, FlaskConical } from 'lucide-react';
import { useState } from 'react';
import AnimatedBackground from './AnimatedBackground';

const dataModels = [
    {
        id: 'camera',
        icon: Camera,
        name: 'Camera',
        color: 'blue',
        gradient: 'from-blue-500 to-cyan-500',
        description: '40 camera entities với sosa:Sensor type',
        details: 'Monitors: vehicleType, speed, location, timestamp. Relationships: sosa:observes, sosa:isHostedBy, sosa:madeObservation',
        entities: 40,
        updateFreq: '30-60s',
    },
    {
        id: 'weather',
        icon: Cloud,
        name: 'WeatherObserved',
        color: 'purple',
        gradient: 'from-purple-500 to-pink-500',
        description: '80 entities từ OpenWeatherMap API',
        details: 'Properties: temperature, humidity, pressure, windSpeed, weatherType. External API integration với real-time updates',
        entities: 80,
        updateFreq: '10min',
    },
    {
        id: 'airquality',
        icon: Wind,
        name: 'AirQualityObserved',
        color: 'green',
        gradient: 'from-green-500 to-emerald-500',
        description: '80 entities từ OpenAQ v3 API',
        details: 'Pollutants: PM2.5, PM10, NO2, O3, CO, SO2. AQI calculation và health advisory generation',
        entities: 80,
        updateFreq: '1hour',
    },
    {
        id: 'itemflow',
        icon: TrendingUp,
        name: 'ItemFlowObserved',
        color: 'orange',
        gradient: 'from-orange-500 to-red-500',
        description: 'Generated by YOLOX Computer Vision',
        details: 'Vehicle counts by type: car, truck, motorcycle, bus. Speed analysis, occupancy calculation, flow rate metrics',
        entities: 'Dynamic',
        updateFreq: 'Real-time',
    },
    {
        id: 'accident',
        icon: AlertTriangle,
        name: 'RoadAccident',
        color: 'red',
        gradient: 'from-red-500 to-pink-500',
        description: 'Anomaly detection từ AI agents',
        details: 'Severity levels, location, timestamp, affected vehicles. AI verification với AccidentDetector agent',
        entities: 'Event-based',
        updateFreq: 'On-demand',
    },
    {
        id: 'pattern',
        icon: Database,
        name: 'TrafficPattern',
        color: 'indigo',
        gradient: 'from-indigo-500 to-purple-500',
        description: 'Time-series pattern analysis',
        details: 'Historical patterns, peak hours, congestion zones. ML-powered prediction với Pattern Recognition Agent',
        entities: 'Analytical',
        updateFreq: '15min',
    },
    {
        id: 'property',
        icon: FlaskConical,
        name: 'ObservableProperty',
        color: 'cyan',
        gradient: 'from-cyan-500 to-blue-500',
        description: 'SOSA/SSN Ontology singleton',
        details: 'Defines observable properties: vehicleType, speed, temperature, pollutants. W3C SOSA/SSN compliant',
        entities: 1,
        updateFreq: 'Static',
    },
    {
        id: 'platform',
        icon: MapPin,
        name: 'Platform',
        color: 'teal',
        gradient: 'from-teal-500 to-cyan-500',
        description: 'HCMC Traffic System singleton',
        details: 'sosa:Platform representing entire system. Hosts all sensors, defines coverage area, system metadata',
        entities: 1,
        updateFreq: 'Static',
    },
    {
        id: 'citizen',
        icon: Users,
        name: 'CitizenObservation',
        color: 'pink',
        gradient: 'from-pink-500 to-rose-500',
        description: 'Mobile app citizen reports',
        details: 'Category, description, imageSnapshot, location. AI verification với YOLOX, weather/AQ context enrichment',
        entities: 'Community',
        updateFreq: 'User-driven',
    },
    {
        id: 'user',
        icon: Users,
        name: 'User',
        color: 'violet',
        gradient: 'from-violet-500 to-purple-500',
        description: 'Citizen reporter profiles',
        details: 'userId, reportCount, verifiedReportCount, accuracyRate. Gamification và reputation tracking',
        entities: 'Community',
        updateFreq: 'On-report',
    },
];

export default function DataModelsShowcase() {
    const [selectedModel, setSelectedModel] = useState(dataModels[0]);

    return (
        <section id="data-models" className="relative py-32 bg-gradient-to-br from-orange-50 via-amber-50 to-yellow-50 overflow-hidden">
            {/* Animated Background */}
            <AnimatedBackground />

            {/* Mesh Gradient Overlay */}
            <div className="absolute inset-0 bg-gradient-to-bl from-orange-100/30 via-transparent to-amber-100/30" />

            {/* Animated Glow Effects */}
            <div className="absolute top-1/3 right-1/3 w-96 h-96 bg-orange-400/20 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '6s' }} />
            <div className="absolute bottom-1/3 left-1/3 w-96 h-96 bg-yellow-400/20 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '8s', animationDelay: '1.5s' }} />

            {/* Background Grid */}
            <div className="absolute inset-0 opacity-30">
                <div className="absolute inset-0" style={{
                    backgroundImage: `linear-gradient(to right, rgb(203 213 225 / 0.3) 1px, transparent 1px), linear-gradient(to bottom, rgb(203 213 225 / 0.3) 1px, transparent 1px)`,
                    backgroundSize: '60px 60px'
                }} />
            </div>

            <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Section Header */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.6 }}
                    className="text-center mb-20"
                >
                    <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-50 border border-blue-100 mb-6">
                        <span className="text-sm font-semibold text-blue-900">NGSI-LD Compliant</span>
                    </div>
                    <h2 className="text-5xl md:text-6xl font-bold mb-6">
                        <span className="bg-clip-text text-transparent bg-gradient-to-r from-slate-900 via-blue-900 to-slate-900">
                            10 Smart Data Models
                        </span>
                    </h2>
                    <p className="text-xl text-slate-600 max-w-3xl mx-auto">
                        Mô hình dữ liệu tuân thủ chuẩn NGSI-LD và SOSA/SSN ontologies,
                        đảm bảo khả năng tương tác và tích hợp với hệ thống quốc tế
                    </p>
                </motion.div>

                {/* Interactive Display */}
                <div className="grid lg:grid-cols-2 gap-12 items-start">
                    {/* Model Cards Grid */}
                    <div className="grid grid-cols-2 gap-4">
                        {dataModels.map((model, index) => (
                            <motion.button
                                key={model.id}
                                initial={{ opacity: 0, scale: 0.9 }}
                                whileInView={{ opacity: 1, scale: 1 }}
                                viewport={{ once: true }}
                                transition={{ duration: 0.3, delay: index * 0.05 }}
                                onClick={() => setSelectedModel(model)}
                                className={`group relative p-6 rounded-2xl transition-all duration-300 text-left ${selectedModel.id === model.id
                                    ? 'bg-white shadow-xl shadow-slate-300/50 scale-105'
                                    : 'bg-white/50 hover:bg-white shadow-md shadow-slate-200/50 hover:shadow-lg'
                                    }`}
                            >
                                {/* Selected Indicator */}
                                {selectedModel.id === model.id && (
                                    <motion.div
                                        layoutId="selectedIndicator"
                                        className={`absolute inset-0 rounded-2xl bg-gradient-to-br ${model.gradient} opacity-10`}
                                    />
                                )}

                                <div className="relative">
                                    {/* Icon */}
                                    <div className={`inline-flex items-center justify-center w-12 h-12 rounded-xl bg-gradient-to-br ${model.gradient} mb-4 shadow-md`}>
                                        <model.icon className="w-6 h-6 text-white" />
                                    </div>

                                    {/* Name */}
                                    <h3 className="font-bold text-slate-900 mb-2 text-lg">
                                        {model.name}
                                    </h3>

                                    {/* Description */}
                                    <p className="text-sm text-slate-600 line-clamp-2">
                                        {model.description}
                                    </p>
                                </div>
                            </motion.button>
                        ))}
                    </div>

                    {/* Selected Model Details */}
                    <motion.div
                        key={selectedModel.id}
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ duration: 0.4 }}
                        className="lg:sticky lg:top-32"
                    >
                        <div className="relative bg-white rounded-3xl p-10 shadow-2xl shadow-slate-300/50 border border-slate-100 overflow-hidden">
                            {/* Gradient Background */}
                            <div className={`absolute top-0 right-0 w-96 h-96 bg-gradient-to-br ${selectedModel.gradient} opacity-5 rounded-full blur-3xl`} />

                            {/* Content */}
                            <div className="relative">
                                {/* Header */}
                                <div className="flex items-start gap-6 mb-8">
                                    <div className={`flex items-center justify-center w-20 h-20 rounded-2xl bg-gradient-to-br ${selectedModel.gradient} shadow-xl`}>
                                        <selectedModel.icon className="w-10 h-10 text-white" />
                                    </div>
                                    <div className="flex-1">
                                        <h3 className="text-3xl font-bold text-slate-900 mb-2">
                                            {selectedModel.name}
                                        </h3>
                                        <p className="text-slate-600">
                                            {selectedModel.description}
                                        </p>
                                    </div>
                                </div>

                                {/* Stats Grid */}
                                <div className="grid grid-cols-2 gap-4 mb-8">
                                    <div className="p-4 rounded-xl bg-slate-50 border border-slate-100">
                                        <div className="text-sm text-slate-600 mb-1">Entities</div>
                                        <div className="text-2xl font-bold text-slate-900">
                                            {selectedModel.entities}
                                        </div>
                                    </div>
                                    <div className="p-4 rounded-xl bg-slate-50 border border-slate-100">
                                        <div className="text-sm text-slate-600 mb-1">Update Freq</div>
                                        <div className="text-2xl font-bold text-slate-900">
                                            {selectedModel.updateFreq}
                                        </div>
                                    </div>
                                </div>

                                {/* Details */}
                                <div className="p-6 rounded-2xl bg-gradient-to-br from-slate-50 to-blue-50 border border-slate-100">
                                    <h4 className="font-semibold text-slate-900 mb-3">Technical Details</h4>
                                    <p className="text-slate-700 leading-relaxed">
                                        {selectedModel.details}
                                    </p>
                                </div>

                                {/* CTA */}
                                <div className="mt-8 flex gap-4">
                                    <button className={`flex-1 px-6 py-3 bg-gradient-to-r ${selectedModel.gradient} text-white rounded-xl font-semibold shadow-lg hover:shadow-xl transition-all duration-300`}>
                                        View Schema
                                    </button>
                                    <button className="px-6 py-3 bg-slate-100 text-slate-900 rounded-xl font-semibold hover:bg-slate-200 transition-colors">
                                        SPARQL Query
                                    </button>
                                </div>
                            </div>
                        </div>
                    </motion.div>
                </div>

                {/* Bottom Info */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.6, delay: 0.3 }}
                    className="mt-20 text-center"
                >
                    <div className="inline-flex items-center gap-8 px-8 py-6 bg-gradient-to-r from-blue-50 to-purple-50 rounded-2xl border border-blue-100">
                        <div className="text-center">
                            <div className="text-3xl font-bold text-slate-900 mb-1">NGSI-LD</div>
                            <div className="text-sm text-slate-600">Context Model</div>
                        </div>
                        <div className="w-px h-12 bg-slate-300" />
                        <div className="text-center">
                            <div className="text-3xl font-bold text-slate-900 mb-1">SOSA/SSN</div>
                            <div className="text-sm text-slate-600">W3C Ontology</div>
                        </div>
                        <div className="w-px h-12 bg-slate-300" />
                        <div className="text-center">
                            <div className="text-3xl font-bold text-slate-900 mb-1">5-Star</div>
                            <div className="text-sm text-slate-600">LOD Rating</div>
                        </div>
                    </div>
                </motion.div>
            </div>
        </section>
    );
}
