/**
 * Health Advisor Chat Component - EcoTwin AI Agent Interface
 * 
 * @module apps/traffic-web-app/frontend/src/components/agents/HealthAdvisorChat
 * @author Nguyễn Nhật Quang
 * @created 2025-11-28
 * @modified 2025-11-28
 * @version 2.0.0
 * @license MIT
 * 
 * @description
 * Interactive chat interface for EcoTwin AI agent providing personalized environmental
 * health advice based on real-time air quality, weather, and user profiles.
 * 
 * Key Features:
 * - Chat bubble interface with message history
 * - Emoji-rich, friendly text generated by Gemini Pro LLM
 * - Smart suggestion interactive buttons:
 *   - "Find cafe with clean air"
 *   - "Show cleaner route"
 *   - "When can I exercise outdoors?"
 *   - "Check AQI forecast"
 * - Dynamic weather animation background matching forecast
 * - Typing indicator for AI responses
 * - Scroll-to-bottom auto-scroll for new messages
 * 
 * User Profiling:
 * - Age group selection (child, adult, elderly)
 * - Health conditions (asthma, heart disease, etc.)
 * - Activity preferences (outdoor exercise, commuting)
 * - Notification preferences
 * 
 * AI Capabilities:
 * - Natural language advice in Vietnamese/English
 * - AQI dispersion simulation (6-hour forecast)
 * - Personalized recommendations for vulnerable populations
 * - Weather-AQI correlation analysis
 * 
 * @dependencies
 * - react@^18.2: UI library
 * - API service for EcoTwin agent backend
 */

import React, { useState, useEffect, useRef } from 'react';

// =====================================================
// TYPE DEFINITIONS
// =====================================================

interface ChatMessage {
    id: string;
    role: 'user' | 'assistant' | 'system';
    content: string;
    timestamp: string;
    metadata?: {
        aqi?: number;
        aqiCategory?: string;
        weather?: {
            condition: string;
            temperature: number;
            humidity: number;
            rainfall: number;
        };
        location?: {
            lat: number;
            lng: number;
            name: string;
        };
    };
    suggestions?: SmartSuggestion[];
}

interface SmartSuggestion {
    id: string;
    type: 'route' | 'location' | 'timing' | 'activity' | 'protection';
    label: string;
    icon: string;
    action: string;
    data?: any;
}

interface UserProfile {
    name: string;
    avatar?: string;
    healthConditions: string[];
    sensitivityLevel: 'low' | 'medium' | 'high';
    preferredLanguage: 'vi' | 'en';
    transportMode: 'walking' | 'bicycle' | 'motorbike' | 'car' | 'public_transport';
}

interface WeatherAnimation {
    type: 'sunny' | 'cloudy' | 'rainy' | 'stormy' | 'foggy' | 'night';
    intensity: 'light' | 'moderate' | 'heavy';
}

interface HealthAdvisorChatProps {
    userProfile: UserProfile;
    initialMessages?: ChatMessage[];
    currentWeather: {
        condition: string;
        temperature: number;
        humidity: number;
        rainfall: number;
        windSpeed: number;
    };
    currentAQI: {
        value: number;
        category: string;
        pm25: number;
        pm10: number;
    };
    onSendMessage?: (message: string) => Promise<ChatMessage>;
    onSuggestionClick?: (suggestion: SmartSuggestion) => void;
    isTyping?: boolean;
}

// =====================================================
// WEATHER ANIMATION COMPONENT
// =====================================================

const WeatherBackground: React.FC<{ animation: WeatherAnimation }> = ({ animation }) => {
    const [particles, setParticles] = useState<Array<{ id: number; x: number; y: number; speed: number }>>([]);

    useEffect(() => {
        if (animation.type === 'rainy' || animation.type === 'stormy') {
            const count = animation.intensity === 'heavy' ? 50 : animation.intensity === 'moderate' ? 30 : 15;
            const newParticles = Array.from({ length: count }, (_, i) => ({
                id: i,
                x: Math.random() * 100,
                y: Math.random() * 100,
                speed: Math.random() * 2 + 1
            }));
            setParticles(newParticles);
        }
    }, [animation]);

    const getBackgroundGradient = () => {
        switch (animation.type) {
            case 'sunny':
                return 'bg-gradient-to-br from-blue-400 via-blue-300 to-yellow-200';
            case 'cloudy':
                return 'bg-gradient-to-br from-gray-400 via-gray-300 to-gray-200';
            case 'rainy':
                return 'bg-gradient-to-br from-gray-600 via-gray-500 to-blue-400';
            case 'stormy':
                return 'bg-gradient-to-br from-gray-800 via-gray-700 to-purple-900';
            case 'foggy':
                return 'bg-gradient-to-br from-gray-300 via-gray-200 to-white';
            case 'night':
                return 'bg-gradient-to-br from-indigo-900 via-purple-900 to-gray-900';
            default:
                return 'bg-gradient-to-br from-blue-300 to-blue-100';
        }
    };

    return (
        <div className={`absolute inset-0 overflow-hidden ${getBackgroundGradient()} transition-all duration-1000`}>
            {/* Sun */}
            {animation.type === 'sunny' && (
                <div className="absolute top-10 right-10 w-20 h-20 bg-yellow-400 rounded-full animate-pulse shadow-2xl">
                    <div className="absolute inset-0 bg-yellow-300 rounded-full animate-ping opacity-75"></div>
                </div>
            )}

            {/* Clouds */}
            {(animation.type === 'cloudy' || animation.type === 'rainy') && (
                <>
                    <div className="absolute top-20 left-10 w-32 h-16 bg-white rounded-full opacity-80 animate-float-slow"></div>
                    <div className="absolute top-32 right-20 w-40 h-20 bg-white rounded-full opacity-70 animate-float-medium"></div>
                    <div className="absolute top-10 left-1/2 w-36 h-18 bg-white rounded-full opacity-75 animate-float-fast"></div>
                </>
            )}

            {/* Rain drops */}
            {(animation.type === 'rainy' || animation.type === 'stormy') && (
                <div className="absolute inset-0">
                    {particles.map((particle) => (
                        <div
                            key={particle.id}
                            className="absolute w-1 h-4 bg-blue-300 opacity-60 animate-rain"
                            style={{
                                left: `${particle.x}%`,
                                top: `${particle.y}%`,
                                animationDuration: `${particle.speed}s`
                            }}
                        ></div>
                    ))}
                </div>
            )}

            {/* Lightning */}
            {animation.type === 'stormy' && (
                <div className="absolute inset-0 animate-lightning opacity-0"></div>
            )}

            {/* Fog */}
            {animation.type === 'foggy' && (
                <>
                    <div className="absolute inset-0 bg-white opacity-40 animate-pulse"></div>
                    <div className="absolute inset-0 bg-gradient-to-t from-transparent to-white opacity-30 animate-float-slow"></div>
                </>
            )}

            {/* Stars */}
            {animation.type === 'night' && (
                <div className="absolute inset-0">
                    {[...Array(20)].map((_, i) => (
                        <div
                            key={i}
                            className="absolute w-1 h-1 bg-white rounded-full animate-twinkle"
                            style={{
                                left: `${Math.random() * 100}%`,
                                top: `${Math.random() * 100}%`,
                                animationDelay: `${Math.random() * 3}s`
                            }}
                        ></div>
                    ))}
                </div>
            )}
        </div>
    );
};

// =====================================================
// MAIN COMPONENT
// =====================================================

export const HealthAdvisorChat: React.FC<HealthAdvisorChatProps> = ({
    userProfile,
    initialMessages = [],
    currentWeather,
    currentAQI,
    onSendMessage,
    onSuggestionClick,
    isTyping = false
}) => {
    const [messages, setMessages] = useState<ChatMessage[]>(initialMessages);
    const [inputMessage, setInputMessage] = useState('');
    const [isSending, setIsSending] = useState(false);
    const messagesEndRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLInputElement>(null);

    // =====================================================
    // DETERMINE WEATHER ANIMATION
    // =====================================================

    const weatherAnimation: WeatherAnimation = (() => {
        const condition = currentWeather.condition.toLowerCase();
        const rainfall = currentWeather.rainfall;

        if (condition.includes('storm') || condition.includes('thunder')) {
            return { type: 'stormy', intensity: 'heavy' };
        }
        if (condition.includes('rain') || rainfall > 0) {
            return {
                type: 'rainy',
                intensity: rainfall > 10 ? 'heavy' : rainfall > 5 ? 'moderate' : 'light'
            };
        }
        if (condition.includes('fog') || condition.includes('mist')) {
            return { type: 'foggy', intensity: 'moderate' };
        }
        if (condition.includes('cloud') || condition.includes('overcast')) {
            return { type: 'cloudy', intensity: 'moderate' };
        }
        if (condition.includes('clear') || condition.includes('sunny')) {
            const hour = new Date().getHours();
            if (hour >= 18 || hour < 6) {
                return { type: 'night', intensity: 'light' };
            }
            return { type: 'sunny', intensity: 'light' };
        }
        return { type: 'cloudy', intensity: 'light' };
    })();

    // =====================================================
    // AUTO-SCROLL TO BOTTOM
    // =====================================================

    useEffect(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [messages, isTyping]);

    // =====================================================
    // SEND MESSAGE HANDLER
    // =====================================================

    const handleSendMessage = async () => {
        if (!inputMessage.trim() || isSending) return;

        const userMessage: ChatMessage = {
            id: `user_${Date.now()}`,
            role: 'user',
            content: inputMessage,
            timestamp: new Date().toISOString()
        };

        setMessages((prev) => [...prev, userMessage]);
        setInputMessage('');
        setIsSending(true);

        try {
            if (onSendMessage) {
                const response = await onSendMessage(inputMessage);
                setMessages((prev) => [...prev, response]);
            } else {
                // Mock response for demo
                setTimeout(() => {
                    const mockResponse: ChatMessage = {
                        id: `assistant_${Date.now()}`,
                        role: 'assistant',
                        content: `Cảm ơn bạn đã hỏi! 🌤️ Tôi đang phân tích dữ liệu không khí và thời tiết để đưa ra lời khuyên tốt nhất cho bạn.`,
                        timestamp: new Date().toISOString(),
                        metadata: {
                            aqi: currentAQI.value,
                            aqiCategory: currentAQI.category,
                            weather: currentWeather
                        },
                        suggestions: [
                            {
                                id: 'sug_1',
                                type: 'location',
                                label: 'Tìm quán cafe gần đây',
                                icon: '☕',
                                action: 'find_cafe'
                            },
                            {
                                id: 'sug_2',
                                type: 'route',
                                label: 'Xem tuyến đường sạch hơn',
                                icon: '🗺️',
                                action: 'show_cleaner_route'
                            }
                        ]
                    };
                    setMessages((prev) => [...prev, mockResponse]);
                    setIsSending(false);
                }, 1500);
                return;
            }
        } catch (error) {
            console.error('Failed to send message:', error);
        } finally {
            setIsSending(false);
        }
    };

    // =====================================================
    // AQI COLOR
    // =====================================================

    const getAQIColor = (aqi: number) => {
        if (aqi <= 50) return 'bg-green-500';
        if (aqi <= 100) return 'bg-yellow-500';
        if (aqi <= 150) return 'bg-orange-500';
        if (aqi <= 200) return 'bg-red-500';
        if (aqi <= 300) return 'bg-purple-500';
        return 'bg-maroon-500';
    };

    // =====================================================
    // SUGGESTION HANDLER
    // =====================================================

    const handleSuggestionClick = (suggestion: SmartSuggestion) => {
        if (onSuggestionClick) {
            onSuggestionClick(suggestion);
        }

        // Add user message showing they clicked the suggestion
        const userMessage: ChatMessage = {
            id: `user_sug_${Date.now()}`,
            role: 'user',
            content: `${suggestion.icon} ${suggestion.label}`,
            timestamp: new Date().toISOString()
        };
        setMessages((prev) => [...prev, userMessage]);
    };

    // =====================================================
    // RENDER MESSAGE
    // =====================================================

    const renderMessage = (message: ChatMessage) => {
        const isUser = message.role === 'user';
        const isSystem = message.role === 'system';

        if (isSystem) {
            return (
                <div key={message.id} className="flex justify-center mb-4">
                    <div className="bg-gray-300 text-gray-700 px-4 py-2 rounded-full text-xs font-semibold">
                        {message.content}
                    </div>
                </div>
            );
        }

        return (
            <div key={message.id} className={`flex mb-4 ${isUser ? 'justify-end' : 'justify-start'}`}>
                <div className={`flex items-start space-x-2 max-w-[70%] ${isUser ? 'flex-row-reverse space-x-reverse' : ''}`}>
                    {/* Avatar */}
                    <div className={`flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center text-xl ${isUser ? 'bg-gray-900 text-white' : 'bg-gray-100 text-gray-900'
                        }`}>
                        {isUser ? (userProfile.avatar || '👤') : '🌿'}
                    </div>

                    {/* Message bubble */}
                    <div>
                        <div className={`rounded-2xl px-4 py-3 shadow-sm ${isUser
                            ? 'bg-gray-900 text-white rounded-tr-none'
                            : 'bg-gray-50 text-gray-900 border border-gray-200 rounded-tl-none'
                            }`}>
                            <p className="text-sm leading-relaxed whitespace-pre-wrap">{message.content}</p>

                            {/* Metadata */}
                            {message.metadata && !isUser && (
                                <div className="mt-2 pt-2 border-t border-green-100 text-xs text-gray-600 space-y-1">
                                    {message.metadata.aqi !== undefined && (
                                        <div className="flex items-center space-x-2">
                                            <span className={`w-3 h-3 rounded-full ${getAQIColor(message.metadata.aqi)}`}></span>
                                            <span>AQI: {message.metadata.aqi} ({message.metadata.aqiCategory})</span>
                                        </div>
                                    )}
                                    {message.metadata.weather && (
                                        <div className="flex items-center space-x-2">
                                            <span>🌡️</span>
                                            <span>{message.metadata.weather.temperature}°C, {message.metadata.weather.condition}</span>
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>

                        {/* Timestamp */}
                        <div className={`text-xs text-gray-500 mt-1 ${isUser ? 'text-right' : 'text-left'}`}>
                            {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </div>

                        {/* Smart suggestions */}
                        {message.suggestions && message.suggestions.length > 0 && (
                            <div className="mt-3 space-y-2">
                                {message.suggestions.map((suggestion) => (
                                    <button
                                        key={suggestion.id}
                                        onClick={() => handleSuggestionClick(suggestion)}
                                        className="flex items-center space-x-2 bg-gradient-to-r from-green-400 to-blue-500 text-white px-4 py-2 rounded-full shadow-md hover:shadow-lg transition-all hover:scale-105 text-sm font-semibold"
                                    >
                                        <span className="text-lg">{suggestion.icon}</span>
                                        <span>{suggestion.label}</span>
                                    </button>
                                ))}
                            </div>
                        )}
                    </div>
                </div>
            </div>
        );
    };

    // =====================================================
    // TYPING INDICATOR
    // =====================================================

    const TypingIndicator = () => (
        <div className="flex justify-start mb-4">
            <div className="flex items-start space-x-2 max-w-[70%]">
                <div className="flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center text-xl bg-gray-100 text-gray-900 shadow-sm border border-gray-200">
                    🌿
                </div>
                <div className="bg-gray-50 text-gray-900 border border-gray-200 rounded-2xl rounded-tl-none px-4 py-3 shadow-sm">
                    <div className="flex space-x-2">
                        <div className="w-2 h-2 bg-gray-600 rounded-full animate-bounce" style={{ animationDelay: '0s' }}></div>
                        <div className="w-2 h-2 bg-gray-600 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
                        <div className="w-2 h-2 bg-gray-600 rounded-full animate-bounce" style={{ animationDelay: '0.4s' }}></div>
                    </div>
                </div>
            </div>
        </div>
    );

    // =====================================================
    // MAIN RENDER
    // =====================================================

    return (
        <div className="relative w-full h-full flex flex-col overflow-hidden rounded-xl shadow-2xl">

            {/* DYNAMIC WEATHER BACKGROUND */}
            <WeatherBackground animation={weatherAnimation} />

            {/* OVERLAY CONTENT */}
            <div className="relative z-10 flex flex-col h-full bg-black bg-opacity-20 backdrop-blur-sm">

                {/* HEADER */}
                <div className="p-4 shadow-lg" style={{ backgroundColor: '#111827', color: 'white' }}>
                    <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-3">
                            <div className="w-10 h-10 bg-white rounded-xl flex items-center justify-center text-2xl shadow-sm">🌿</div>
                            <div>
                                <h2 className="text-xl font-bold text-white">Eco-Twin Health Advisor</h2>
                                <p className="text-sm text-gray-300">
                                    Lời khuyên thông minh về sức khỏe và môi trường
                                </p>
                            </div>
                        </div>
                        <div className="flex items-center space-x-3">
                            {/* AQI Badge */}
                            <div className={`${getAQIColor(currentAQI.value)} text-white px-3 py-1 rounded-lg text-sm font-bold shadow-sm`}>
                                AQI {currentAQI.value}
                            </div>
                            {/* Weather Badge */}
                            <div className="bg-white px-3 py-1 rounded-lg text-sm font-semibold shadow-sm" style={{ color: '#111827' }}>
                                🌡️ {currentWeather.temperature}°C
                            </div>
                        </div>
                    </div>
                </div>

                {/* USER PROFILE BAR */}
                <div className="bg-white p-3 border-b" style={{ borderColor: '#E5E7EB' }}>
                    <div className="flex items-center justify-between text-sm">
                        <div className="flex items-center space-x-2">
                            <div className="w-8 h-8 rounded-full text-white flex items-center justify-center text-lg shadow-sm" style={{ backgroundColor: '#111827' }}>
                                {userProfile.avatar || '👤'}
                            </div>
                            <div>
                                <p className="font-semibold" style={{ color: '#111827' }}>{userProfile.name}</p>
                                <p className="text-xs text-gray-500">
                                    {userProfile.transportMode} • {userProfile.sensitivityLevel} sensitivity
                                </p>
                            </div>
                        </div>
                        <div className="flex items-center space-x-1 text-xs text-gray-600">
                            {userProfile.healthConditions.length > 0 ? (
                                <>
                                    <span>⚕️</span>
                                    <span>{userProfile.healthConditions.join(', ')}</span>
                                </>
                            ) : (
                                <>
                                    <span>✅</span>
                                    <span>Healthy</span>
                                </>
                            )}
                        </div>
                    </div>
                </div>

                {/* MESSAGES AREA - WITH SCROLL */}
                <div className="flex-1 p-4 space-y-4 bg-white overflow-y-auto" style={{ maxHeight: 'calc(100vh - 400px)' }}>
                    {messages.length === 0 && (
                        <div className="flex flex-col items-center justify-center h-full text-center space-y-4">
                            <div className="text-6xl">🌿💬</div>
                            <p className="text-lg font-semibold text-gray-700">
                                Xin chào {userProfile.name}! 👋
                            </p>
                            <p className="text-sm text-gray-600 max-w-md">
                                Tôi là trợ lý Eco-Twin của bạn. Hỏi tôi về chất lượng không khí, thời tiết,
                                hoặc cách bảo vệ sức khỏe khi di chuyển! ☕🌧️
                            </p>
                        </div>
                    )}

                    {messages.map(renderMessage)}

                    {(isTyping || isSending) && <TypingIndicator />}

                    <div ref={messagesEndRef} />
                </div>

                {/* INPUT AREA */}
                <div className="bg-white p-4 border-t border-gray-200 shadow-lg">
                    <div className="flex items-center space-x-2">
                        <input
                            ref={inputRef}
                            type="text"
                            value={inputMessage}
                            onChange={(e) => setInputMessage(e.target.value)}
                            onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
                            placeholder={
                                userProfile.preferredLanguage === 'vi'
                                    ? 'Nhập tin nhắn của bạn...'
                                    : 'Type your message...'
                            }
                            className="flex-1 px-4 py-3 border-2 rounded-full focus:outline-none transition-colors"
                            style={{ borderColor: '#E5E7EB', color: '#111827' }}
                            disabled={isSending}
                        />
                        <button
                            onClick={handleSendMessage}
                            disabled={!inputMessage.trim() || isSending}
                            className={`px-6 py-3 rounded-full font-semibold transition-all ${inputMessage.trim() && !isSending
                                ? 'text-white hover:shadow-lg hover:scale-105'
                                : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                                }`}
                            style={inputMessage.trim() && !isSending ? { backgroundColor: '#111827' } : undefined}
                        >
                            {isSending ? '⏳' : '📤'}
                        </button>
                    </div>

                    {/* Quick Actions */}
                    <div className="mt-3 flex items-center space-x-2 overflow-x-auto pb-2">
                        <span className="text-xs text-gray-600 font-semibold whitespace-nowrap">Quick Ask:</span>
                        {[
                            { label: 'Có nên ra ngoài không?', icon: '🚶' },
                            { label: 'Thời tiết hôm nay', icon: '🌤️' },
                            { label: 'Tuyến đường sạch', icon: '🗺️' },
                            { label: 'Quán cafe gần đây', icon: '☕' }
                        ].map((quick, index) => (
                            <button
                                key={index}
                                onClick={() => setInputMessage(quick.label)}
                                className="flex items-center space-x-1 px-3 py-1 bg-gray-100 hover:bg-gray-200 rounded-full text-xs font-medium text-gray-700 transition-colors whitespace-nowrap"
                            >
                                <span>{quick.icon}</span>
                                <span>{quick.label}</span>
                            </button>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
};

// =====================================================
// CUSTOM ANIMATIONS (Add to global CSS or Tailwind config)
// =====================================================

const styles = `
@keyframes float-slow {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-20px); }
}

@keyframes float-medium {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-15px); }
}

@keyframes float-fast {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-10px); }
}

@keyframes rain {
  0% { transform: translateY(-100px); opacity: 0; }
  10% { opacity: 1; }
  90% { opacity: 1; }
  100% { transform: translateY(100vh); opacity: 0; }
}

@keyframes lightning {
  0%, 90%, 100% { opacity: 0; }
  92%, 94% { opacity: 1; background-color: white; }
}

@keyframes twinkle {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.3; }
}

.animate-float-slow {
  animation: float-slow 8s ease-in-out infinite;
}

.animate-float-medium {
  animation: float-medium 6s ease-in-out infinite;
}

.animate-float-fast {
  animation: float-fast 4s ease-in-out infinite;
}

.animate-rain {
  animation: rain 1s linear infinite;
}

.animate-lightning {
  animation: lightning 3s ease-in-out infinite;
}

.animate-twinkle {
  animation: twinkle 2s ease-in-out infinite;
}
`;

// Inject styles
if (typeof document !== 'undefined') {
    const styleSheet = document.createElement('style');
    styleSheet.textContent = styles;
    document.head.appendChild(styleSheet);
}

export default HealthAdvisorChat;
